default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  username: <%= ENV['HS_DATABASE_USERNAME'] %>
  password: <%= ENV['HS_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: hs_development

test:
  <<: *default
  database: hs_test

production:
  <<: *default
  database: hs_production
